steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/radio-monitor:latest', '-f', 'app/Dockerfile', 'app/.' ]
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push','gcr.io/${PROJECT_ID}/radio-monitor:latest']
# - name: 'gcr.io/cloud-builders/docker'
#   args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/radio-monitor:latest-deepspeech', '-f', 'app/deepspeech.Dockerfile', 'app/.' ]
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push','gcr.io/${PROJECT_ID}/radio-monitor:latest-deepspeech']
- name: 'gcr.io/cloud-builders/gke-deploy'
  entrypoint: 'bash'
  args:
    - -c
    - |
      export PROJECT_ID=${PROJECT_ID}
      export RADIO_NFS_IPADDRESS=$(gcloud filestore instances describe radio-monitor --project=${PROJECT_ID} --zone=australia-southeast1-a --format="get(networks[0].ipAddresses[0])")
      kustomize build infra > combined.yaml
      envsubst '$${PROJECT_ID},$${RADIO_NFS_IPADDRESS}' < combined.yaml > subbed.yaml
      gke-deploy apply -f subbed.yaml --cluster radio-monitor --location australia-southeast1
# images:
#   - gcr.io/${PROJECT_ID}/radio-monitor:latest
#   - gcr.io/${PROJECT_ID}/radio-monitor:latest-deepspeech
