steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', 
  '-t', 'gcr.io/${PROJECT_ID}/radio-monitor:latest-base', 
  '-f', 'app/dockerfiles/base.Dockerfile', 'app/.']

images:
  - gcr.io/${PROJECT_ID}/radio-monitor:latest-base
