steps:
  #- name: 'gcr.io/cloud-builders/docker'
  #args: ['build', 
  #'-t', 'gcr.io/${PROJECT_ID}/radio-monitor:latest-base', 
  #'-f', 'app/dockerfiles/base.Dockerfile', 'app/.']
  #
  #- name: 'gcr.io/cloud-builders/docker'
  #args: ['push', 
  #'gcr.io/${PROJECT_ID}/radio-monitor:latest-base']
  #
- name: 'gcr.io/cloud-builders/gke-deploy'
  entrypoint: 'kustomize'
  args:
    - 'build'
    - 'infra'
    - '-o'
    - 'infra/resources.yaml'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=australia-southeast1'
    - 'CLOUDSDK_CONTAINER_CLUSTER=radio-monitor'
  
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
    - 'run'
    - '-f'
    - '/workspace/infra/resources.yaml'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=australia-southeast1'
    - 'CLOUDSDK_CONTAINER_CLUSTER=radio-monitor'
