steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/radio-monitor:latest', '-f', 'app/Dockerfile', 'app/.' ]
# - name: 'gcr.io/cloud-builders/docker'
#   args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/radio-monitor:latest-deepspeech', '-f', 'app/deepspeech.Dockerfile', 'app/.' ]
- name: 'gcr.io/cloud-builders/gke-deploy'
  entrypoint: 'bash'
  args:
    - -c
    - |
      kustomize build infra | gke-deploy apply -f - --cluster radio-monitor --location australia-southeast1
