steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/radio-monitor:latest', '-f', 'app/Dockerfile', 'app/.' ]
# - name: 'gcr.io/cloud-builders/docker'
#   args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/radio-monitor:latest-deepspeech', '-f', 'app/deepspeech.Dockerfile', 'app/.' ]
- name: 'gcr.io/cloud-builders/gke-deploy'
  entrypoint: 'bash'
  args:
    - -c
    - |
      kustomize build infra | gke-deploy apply -f - --cluster radio-monitor --location australia-southeast1
  #   - apply
  #   - -k
  #   - infra/kustomization.yaml
  # env:
  #   - CLOUDSDK_COMPUTE_REGION=australia-southeast1-a
  #   - CLOUDSDK_CONTAINER_CLUSTER=radio-monitor
# - name: 'gcr.io/cloud-builders/gke-deploy'
#   args:
#     - 'run'
#     - '-f'
#     - '/workspace/all_resources.yaml'
# - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
#   entrypoint: "bash"
#   waitFor: ["-"]
#   args:
#     - "-c"
#     - |
#       export BRANCH_NAME=${BRANCH_NAME}
#       export PROJECT_ID=${PROJECT_ID}
#       source config.sh
#       cd app/python
#       gcloud builds submit --timeout=3600s --tag gcr.io/$${PROJECT_ID}/python
  #- name: 'gcr.io/cloud-builders/docker'
  #args: ['build', 
  #'-t', 'gcr.io/${PROJECT_ID}/radio-monitor:latest-base', 
  #'-f', 'app/dockerfiles/base.Dockerfile', 'app/.']
  #
  #- name: 'gcr.io/cloud-builders/docker'
  #args: ['push', 
  #'gcr.io/${PROJECT_ID}/radio-monitor:latest-base']
  #
# - name: 'gcr.io/cloud-builders/gke-deploy'
#   entrypoint: 'kustomize'
#   args:
#     - 'build'
#     - 'infra'
#     - '-o'
#     - 'infra/resources.yaml'
#   env:
#     - 'CLOUDSDK_COMPUTE_ZONE=australia-southeast1'
#     - 'CLOUDSDK_CONTAINER_CLUSTER=radio-monitor'
  
# - name: 'gcr.io/cloud-builders/gke-deploy'
#   args:
#     - 'run'
#     - '-f'
#     - '/workspace/infra/resources.yaml'
#   env:
#     - 'CLOUDSDK_COMPUTE_ZONE=australia-southeast1'
#     - 'CLOUDSDK_CONTAINER_CLUSTER=radio-monitor'
