apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/filestore-pv.yaml
- base/gcp-mentions-deployment.yaml
- base/gcp-sentiment-deployment.yaml
- base/gcp-transcriber-deployment.yaml
- base/opensource-mentions-deployment.yaml
- base/opensource-sentiment-deployment.yaml
- base/opensource-transcriber-deployment.yaml
- base/recorder-deployment.yaml
- base/storage-audio-pvc.yaml
- base/storage-transcript-pvc.yaml

- overlays/staging/radio-monitor-secrets.yaml

namespace: default
