apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/mentions-analyser-deployment.yaml
- base/recorder-deployment.yaml
- base/sentiment-analyser-deployment.yaml
- base/storage-audio-pvc.yaml
- base/storage-audio-storageclass.yaml
- base/storage-transcript-pvc.yaml
- base/storage-transcript-storageclass.yaml
#- base/transcriber-deployment-3lo.yaml
# Disable one of the transcribers for cost saving:
# - base/transcriber-deployment-2bl.yaml

- overlays/staging/radio-monitor-config-cm.yaml
- overlays/staging/radio-monitor-secrets.yaml

namespace: radio-monitor
