version: '3'
services: 
    # grafana:
    #     ports:
    #         - "80:3000"
    #     volumes:
    #         - grafana-storage:/var/lib/grafana
    #     environment: 
    #         GF_SERVER_ENABLE_GZIP: "true"
    #         GF_AUTH_ANONYMOUS_ENABLED: "true"
    #         GF_AUTH_ANONYMOUS_ORG_NAME: Eliiza
    #     image: grafana/grafana
    #     restart: on-failure
    # record-3LO:
    #     environment:
    #         STREAM_SRC: http://live-radio01.mediahubaustralia.com/3LRW/mp3/
    #         S3_BUCKET: lucas-radio-streaming
    #         AWS_ACCESS_KEY_ID: AKIAZJBU4EUF5VNMYAIB
    #         AWS_SECRET_ACCESS_KEY: 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
    #     image: eliiza/radio-ffmpeg:1.2.1
    #     restart: on-failure
    #     command: record ffmpeg --output=s3 --sources=3LO
    # record-3AW:
    #     environment:
    #         STREAM_SRC: http://shoutcast.3aw.com.au/3aw/mp3
    #         S3_BUCKET: lucas-radio-streaming
    #         AWS_ACCESS_KEY_ID: AKIAZJBU4EUF5VNMYAIB
    #         AWS_SECRET_ACCESS_KEY: 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
    #     image: eliiza/radio-ffmpeg:1.2.1
    #     restart: on-failure
    #     command: record ffmpeg --output=s3 --sources=3AW
    # transcribe-deepspeech:
    #     environment:
    #         S3_BUCKET: lucas-radio-streaming
    #         AWS_ACCESS_KEY_ID: AKIAZJBU4EUF5VNMYAIB
    #         AWS_SECRET_ACCESS_KEY: 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
    #     image: eliiza/radio-deepspeech:1.2.1_0.7.3
    #     restart: on-failure
    #     command: transcribe deepspeech --input=s3 --output=s3 --sources=3LO:ffmpeg,3AW:ffmpeg
    # transcribe-aws:
    #     environment:
    #         S3_BUCKET: lucas-radio-streaming
    #         AWS_ACCESS_KEY_ID: AKIAZJBU4EUF5VNMYAIB
    #         AWS_SECRET_ACCESS_KEY: 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
    #         AUDIO_SOURCES: 3LO:ffmpeg,3AW:ffmpeg
    #         AWS_TRANSCRIBE_PENDING_BUCKET: lucas-radio-streaming-transcriptions
    #     image: eliiza/radio-base:1.2.0
    #     command: transcribe-with-aws-transcribe
    #     restart: on-failure
    # transcribe-gcp:
    #     volumes:
    #         - ~/Documents/bench/radio-media-monitoring/keys:/root/keys
    #     environment:
    #         S3_BUCKET: lucas-radio-streaming
    #         AWS_ACCESS_KEY_ID: AKIAZJBU4EUF5VNMYAIB
    #         AWS_SECRET_ACCESS_KEY: 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
    #         GOOGLE_APPLICATION_CREDENTIALS: /root/keys/gcp-radio-streaming.json
    #     image: eliiza/radio-base:1.2.1
    #     command: transcribe gcp --input=s3 --output=s3 --sources=3LO:ffmpeg,3AW:ffmpeg
    #     restart: on-failure
    # transcribe-azure:
    #     environment:
    #         S3_BUCKET: lucas-radio-streaming
    #         AWS_ACCESS_KEY_ID: AKIAZJBU4EUF5VNMYAIB
    #         AWS_SECRET_ACCESS_KEY: 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
    #         AZURE_SUBSCRIPTION_KEY: 8e359ac5d5d345deac9c1a851164a406
    #         AUDIO_SOURCES: 3LO:ffmpeg,3AW:ffmpeg
    #     image: eliiza/radio-azuresdk:1.2.0
    #     command: transcribe-with-azure-speech-to-text
    #     restart: on-failure
    # analyse-sentiment-natural:
    #     environment:
    #         S3_BUCKET: lucas-radio-streaming
    #         AWS_ACCESS_KEY_ID: AKIAZJBU4EUF5VNMYAIB
    #         AWS_SECRET_ACCESS_KEY: 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
    #         POSTGRESQL_HOST: lucas-radio-streaming.czyr5fsmnye2.ap-southeast-2.rds.amazonaws.com
    #         POSTGRESQL_DATABASE: radioanalysis
    #         POSTGRESQL_USERNAME: radiostream
    #         POSTGRESQL_PASSWORD: u7oa6gYAYZJ9tCMJodj7sxvLEF35EB
    #     image: eliiza/radio-base:1.2.1
    #     restart: on-failure
    #     command: analyse-sentiment naturaljs --input=s3 --output=postgres --sources=3LO:ffmpeg:deepspeech-0.7.3,3AW:ffmpeg:deepspeech-0.7.3,3LO:ffmpeg:awstranscribe,3AW:ffmpeg:awstranscribe,3LO:ffmpeg:gcpspeechtotext,3AW:ffmpeg:gcpspeechtotext,3LO:ffmpeg:azurespeechtotext,3AW:ffmpeg:azurespeechtotext
    # analyse-mentions-compromise:
    #     environment:
    #         S3_BUCKET: lucas-radio-streaming
    #         AWS_ACCESS_KEY_ID: AKIAZJBU4EUF5VNMYAIB
    #         AWS_SECRET_ACCESS_KEY: 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
    #         POSTGRESQL_HOST: lucas-radio-streaming.czyr5fsmnye2.ap-southeast-2.rds.amazonaws.com
    #         POSTGRESQL_DATABASE: radioanalysis
    #         POSTGRESQL_USERNAME: radiostream
    #         POSTGRESQL_PASSWORD: u7oa6gYAYZJ9tCMJodj7sxvLEF35EB
    #     image: eliiza/radio-base:1.2.1
    #     restart: on-failure
    #     command: analyse-mentions compromisejs --input=s3 --output=postgres --sources=3LO:ffmpeg:deepspeech-0.7.3,3AW:ffmpeg:deepspeech-0.7.3,3LO:ffmpeg:awstranscribe,3AW:ffmpeg:awstranscribe,3LO:ffmpeg:gcpspeechtotext,3AW:ffmpeg:gcpspeechtotext,3LO:ffmpeg:azurespeechtotext,3AW:ffmpeg:azurespeechtotext
    # analyse-sentiment-aws:
    #     environment:
    #         S3_BUCKET: lucas-radio-streaming
    #         AWS_ACCESS_KEY_ID: AKIAZJBU4EUF5VNMYAIB
    #         AWS_SECRET_ACCESS_KEY: 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
    #         POSTGRESQL_HOST: lucas-radio-streaming.czyr5fsmnye2.ap-southeast-2.rds.amazonaws.com
    #         POSTGRESQL_DATABASE: radioanalysis
    #         POSTGRESQL_USERNAME: radiostream
    #         POSTGRESQL_PASSWORD: u7oa6gYAYZJ9tCMJodj7sxvLEF35EB
    #         TRANSCRIPT_SOURCES: 3LO:ffmpeg:deepspeech-0.7.1,3AW:ffmpeg:deepspeech-0.7.1,3LO:ffmpeg:awstranscribe,3AW:ffmpeg:awstranscribe,3LO:ffmpeg:gcpspeechtotext,3AW:ffmpeg:gcpspeechtotext,3LO:ffmpeg:azurespeechtotext,3AW:ffmpeg:azurespeechtotext
    #     image: eliiza/radio-base:1.2.0
    #     command: analyse-sentiment-with-aws-comprehend
    #     restart: on-failure
    analyse-sentiment-gcp:
        volumes:
            - ~/Documents/bench/radio-media-monitoring/keys:/root/keys
        environment:
            S3_BUCKET: lucas-radio-streaming
            AWS_ACCESS_KEY_ID: AKIAZJBU4EUF5VNMYAIB
            AWS_SECRET_ACCESS_KEY: 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
            GOOGLE_APPLICATION_CREDENTIALS: /root/keys/gcp-radio-streaming.json
            POSTGRESQL_HOST: lucas-radio-streaming.czyr5fsmnye2.ap-southeast-2.rds.amazonaws.com
            POSTGRESQL_DATABASE: radioanalysis
            POSTGRESQL_USERNAME: radiostream
            POSTGRESQL_PASSWORD: u7oa6gYAYZJ9tCMJodj7sxvLEF35EB
        image: eliiza/radio-base:1.2.1
        command: analyse-sentiment gcp --input=s3 --output=postgres --sources=3LO:ffmpeg:deepspeech-0.7.3,3AW:ffmpeg:deepspeech-0.7.3,3LO:ffmpeg:awstranscribe,3AW:ffmpeg:awstranscribe,3LO:ffmpeg:gcpspeechtotext,3AW:ffmpeg:gcpspeechtotext,3LO:ffmpeg:azurespeechtotext,3AW:ffmpeg:azurespeechtotext
        restart: on-failure
    # analyse-sentiment-azure:
    #     environment:
    #         S3_BUCKET: lucas-radio-streaming
    #         AWS_ACCESS_KEY_ID: AKIAZJBU4EUF5VNMYAIB
    #         AWS_SECRET_ACCESS_KEY: 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
    #         AZURE_TEXT_ANALYTICS_ENDPOINT: https://australiaeast.api.cognitive.microsoft.com/
    #         AZURE_TEXT_ANALYTICS_KEY: 8e359ac5d5d345deac9c1a851164a406
    #         POSTGRESQL_HOST: lucas-radio-streaming.czyr5fsmnye2.ap-southeast-2.rds.amazonaws.com
    #         POSTGRESQL_DATABASE: radioanalysis
    #         POSTGRESQL_USERNAME: radiostream
    #         POSTGRESQL_PASSWORD: u7oa6gYAYZJ9tCMJodj7sxvLEF35EB
    #         TRANSCRIPT_SOURCES: 3LO:ffmpeg:deepspeech-0.7.1,3AW:ffmpeg:deepspeech-0.7.1,3LO:ffmpeg:awstranscribe,3AW:ffmpeg:awstranscribe,3LO:ffmpeg:gcpspeechtotext,3AW:ffmpeg:gcpspeechtotext,3LO:ffmpeg:azurespeechtotext,3AW:ffmpeg:azurespeechtotext
    #     image: eliiza/radio-azuresdk:1.2.0
    #     command: analyse-sentiment-with-azure-text-analytics
    #     restart: on-failure
    # analyse-mentions-aws:
    #     environment:
    #         S3_BUCKET: lucas-radio-streaming
    #         AWS_ACCESS_KEY_ID: AKIAZJBU4EUF5VNMYAIB
    #         AWS_SECRET_ACCESS_KEY: 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
    #         POSTGRESQL_HOST: lucas-radio-streaming.czyr5fsmnye2.ap-southeast-2.rds.amazonaws.com
    #         POSTGRESQL_DATABASE: radioanalysis
    #         POSTGRESQL_USERNAME: radiostream
    #         POSTGRESQL_PASSWORD: u7oa6gYAYZJ9tCMJodj7sxvLEF35EB
    #         TRANSCRIPT_SOURCES: 3LO:ffmpeg:deepspeech-0.7.1,3AW:ffmpeg:deepspeech-0.7.1,3LO:ffmpeg:awstranscribe,3AW:ffmpeg:awstranscribe,3LO:ffmpeg:gcpspeechtotext,3AW:ffmpeg:gcpspeechtotext,3LO:ffmpeg:azurespeechtotext,3AW:ffmpeg:azurespeechtotext
    #     image: eliiza/radio-base:1.2.0
    #     command: analyse-mentions-with-aws-comprehend
    #     restart: on-failure
    analyse-mentions-gcp:
        volumes:
            - ~/Documents/bench/radio-media-monitoring/keys:/root/keys
        environment:
            S3_BUCKET: lucas-radio-streaming
            AWS_ACCESS_KEY_ID: AKIAZJBU4EUF5VNMYAIB
            AWS_SECRET_ACCESS_KEY: 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
            GOOGLE_APPLICATION_CREDENTIALS: /root/keys/gcp-radio-streaming.json
            POSTGRESQL_HOST: lucas-radio-streaming.czyr5fsmnye2.ap-southeast-2.rds.amazonaws.com
            POSTGRESQL_DATABASE: radioanalysis
            POSTGRESQL_USERNAME: radiostream
            POSTGRESQL_PASSWORD: u7oa6gYAYZJ9tCMJodj7sxvLEF35EB
        image: eliiza/radio-base:1.2.1
        command: analyse-mentions gcp --input=s3 --output=postgres --sources=3LO:ffmpeg:deepspeech-0.7.3,3AW:ffmpeg:deepspeech-0.7.3,3LO:ffmpeg:awstranscribe,3AW:ffmpeg:awstranscribe,3LO:ffmpeg:gcpspeechtotext,3AW:ffmpeg:gcpspeechtotext,3LO:ffmpeg:azurespeechtotext,3AW:ffmpeg:azurespeechtotext
        restart: on-failure
    # analyse-mentions-azure:
    #     environment:
    #         S3_BUCKET: lucas-radio-streaming
    #         AWS_ACCESS_KEY_ID: AKIAZJBU4EUF5VNMYAIB
    #         AWS_SECRET_ACCESS_KEY: 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
    #         AZURE_TEXT_ANALYTICS_ENDPOINT: https://australiaeast.api.cognitive.microsoft.com/
    #         AZURE_TEXT_ANALYTICS_KEY: 8e359ac5d5d345deac9c1a851164a406
    #         POSTGRESQL_HOST: lucas-radio-streaming.czyr5fsmnye2.ap-southeast-2.rds.amazonaws.com
    #         POSTGRESQL_DATABASE: radioanalysis
    #         POSTGRESQL_USERNAME: radiostream
    #         POSTGRESQL_PASSWORD: u7oa6gYAYZJ9tCMJodj7sxvLEF35EB
    #         TRANSCRIPT_SOURCES: 3LO:ffmpeg:deepspeech-0.7.1,3AW:ffmpeg:deepspeech-0.7.1,3LO:ffmpeg:awstranscribe,3AW:ffmpeg:awstranscribe,3LO:ffmpeg:gcpspeechtotext,3AW:ffmpeg:gcpspeechtotext,3LO:ffmpeg:azurespeechtotext,3AW:ffmpeg:azurespeechtotext
    #     image: eliiza/radio-azuresdk:1.2.0
    #     command: analyse-mentions-with-azure-text-analytics
    #     restart: on-failure
volumes:
    grafana-storage: