apiVersion: v1
kind: PersistentVolume
metadata:
  name: radio-monitor-fileserver
spec:
  capacity:
    storage: 1T
  accessModes:
  - ReadWriteMany
  nfs:
    path: /radiomonitor
    server: ${RADIO_NFS_IPADDRESS}