apiVersion: v1
kind: PersistentVolume
metadata:
  name: radio-monitor-fileserver
spec:
  capacity:
    storage: 1T
  accessModes:
  - ReadWriteMany
  nfs:
    path: /radio-monitor
    server: 10.96.141.194