{
 "title": "Real Time Radio Analytics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "source", "label": "Radio Stations", "query": "3LO,2BL" },
   {
    "name": "stt",
    "label": "Speech-to-Text Engine",
    "query": "deepspeech-0.9.3,deepspeech-0.7.3"
   },
   { "name": "mentions", "label": "Mentions Processor", "query": "compromise-13.1.1" },
   { "name": "sentiment", "label": "Sentiment Processor", "query": "natural-0.6.3" }
  ]
 },
 "panels": [
  {
   "title": "Topics Mentioned",
   "type": "table",
   "description": "Count of mentions during the time windows, excluding QUANTITYs",
   "gridPos": { "h": 16, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(\"count\"),\n  entity,\n  category\nFROM mentions\nWHERE\n  $__timeFilter(\"timestamp\")\n  AND split_part(\"sourcechain\", ':', 1) IN (${source})\n  AND split_part(\"sourcechain\", ':', 3) = '${stt}'\n  AND split_part(\"sourcechain\", ':', 4) = '${mentions}'\n  -- AND count > '1'\n  AND category != 'QUANTITY'\nGROUP BY entity, category\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Most Common Mentions",
   "type": "graph",
   "description": "Displays 10 most common mentions and when they were mentioned, within the time period.",
   "gridPos": { "h": 9, "w": 15, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(\"timestamp\", $__interval, 0) as \"time\",\n  sum(\"count\"),\n  \"entity\"\nFROM mentions\nWHERE\n  \"entity\" IN (\n    SELECT \"entity\"\n    FROM mentions\n    WHERE $__timeFilter(\"timestamp\")\n    AND split_part(\"sourcechain\", ':', 1) IN (${source})\n    AND split_part(\"sourcechain\", ':', 3) = '${stt}'\n    AND split_part(\"sourcechain\", ':', 4) = '${mentions}'\n    GROUP BY \"entity\"\n    ORDER BY sum(\"count\") desc\n    LIMIT 10\n  )\n  AND split_part(\"sourcechain\", ':', 1) IN (${source})\n  AND split_part(\"sourcechain\", ':', 3) = '${stt}'\n  AND split_part(\"sourcechain\", ':', 4) = '${mentions}'\n  AND $__timeFilter(\"timestamp\")\nGROUP BY \"entity\", \"timestamp\"\nORDER BY \"timestamp\""
    }
   ]
  },
  {
   "title": "Sentiment over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  (avg(\"positive\" - \"negative\")) AS \"Sentiment\",\n  split_part(\"sourcechain\", ':', 1) AS source\nFROM sentiment\nWHERE\n  $__timeFilter(\"timestamp\")\n  AND split_part(\"sourcechain\", ':', 1) IN (${source})\n  AND split_part(\"sourcechain\", ':', 3) = '${stt}'\n  AND split_part(\"sourcechain\", ':', 4) = '${sentiment}'\nGROUP BY 1, source\nORDER BY 1"
    }
   ]
  }
 ]
}