apiVersion: v1
kind: ServiceAccount
metadata:
  name: radio-monitor-grafana
  labels:
    app: radio-monitor
    component: grafana
  annotations:
    iam.gke.io/gcp-service-account: radio-monitor-postgres@${PROJECT_ID}.iam.gserviceaccount.com