apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: radio-monitor
    component: grafana
spec:
  selector:
    app: radio-monitor
    component: grafana
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000