apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensource-transcriber
  labels:
    app: radio-monitor
    component: opensource-transcriber
spec:
  selector:
    matchLabels:
      app: radio-monitor
      component: opensource-transcriber
  template:
    metadata:
      labels:
        app: radio-monitor
        component: opensource-transcriber
    spec:
      initContainers:
      - name: create-sub-dirs
        image: busybox:stable
        command: ['sh', '-c', 'mkdir -p /mnt/rm-nfs/transcripts/3LO:ffmpeg:opensource']
        volumeMounts:
        - name: nfs
          mountPath: /mnt/rm-nfs
      containers:
      - name: opensource-transcriber-deepspeech
        image: gcr.io/${PROJECT_ID}/radio-monitor:latest-deepspeech
        env:
        - name: AUDIO_DIRECTORY
          value: /mnt/rm-nfs/audio
        - name: TRANSCRIPT_DIRECTORY
          value: /mnt/rm-nfs/transcripts
        - name: DEEPSPEECH_VERSION
          value: "0.9.3"
        - name: DEEPSPEECH_TFLITE
          value: "true"
        args:
        - transcribe
        - opensource
        - --input=fs
        - --output=fs
        - --sources=3LO:ffmpeg
        resources:
          requests:
            cpu: 1500m
            memory: 1000Mi
          limits:
            cpu: 1500m
            memory: 1000Mi
        volumeMounts:
        - name: nfs
          mountPath: /mnt/rm-nfs
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: radio-monitor-nfs