apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audio-blobs
  labels:
    app: radio-monitor
    component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: audio-blobs