apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transcript-blobs
  labels:
    app: radio-monitor
    component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: transcript-blobs