kind: Secret
apiVersion: v1
metadata:
  name: radio-monitor-secrets
stringData:
  postgresHost:  radio-monitor
  postgresDatabase: radio-monitor 
  postgresUsername: radio-monitor 
  postgresPassword: radio-monitor 
